# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.29.2/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.29.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/robk/src/tryhard/esp/lib/sensor_compress

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/robk/src/tryhard/esp/lib/sensor_compress

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.29.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.29.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/robk/src/tryhard/esp/lib/sensor_compress/CMakeFiles /Users/robk/src/tryhard/esp/lib/sensor_compress//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/robk/src/tryhard/esp/lib/sensor_compress/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /Users/robk/src/tryhard/esp/lib/sensor_compress/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sensor_compress

# Build rule for target.
sensor_compress: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sensor_compress
.PHONY : sensor_compress

# fast build rule for target.
sensor_compress/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sensor_compress.dir/build.make CMakeFiles/sensor_compress.dir/build
.PHONY : sensor_compress/fast

src/compress.o: src/compress.cc.o
.PHONY : src/compress.o

# target to build an object file
src/compress.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sensor_compress.dir/build.make CMakeFiles/sensor_compress.dir/src/compress.cc.o
.PHONY : src/compress.cc.o

src/compress.i: src/compress.cc.i
.PHONY : src/compress.i

# target to preprocess a source file
src/compress.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sensor_compress.dir/build.make CMakeFiles/sensor_compress.dir/src/compress.cc.i
.PHONY : src/compress.cc.i

src/compress.s: src/compress.cc.s
.PHONY : src/compress.s

# target to generate assembly for a file
src/compress.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sensor_compress.dir/build.make CMakeFiles/sensor_compress.dir/src/compress.cc.s
.PHONY : src/compress.cc.s

src/data_frame.o: src/data_frame.cc.o
.PHONY : src/data_frame.o

# target to build an object file
src/data_frame.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sensor_compress.dir/build.make CMakeFiles/sensor_compress.dir/src/data_frame.cc.o
.PHONY : src/data_frame.cc.o

src/data_frame.i: src/data_frame.cc.i
.PHONY : src/data_frame.i

# target to preprocess a source file
src/data_frame.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sensor_compress.dir/build.make CMakeFiles/sensor_compress.dir/src/data_frame.cc.i
.PHONY : src/data_frame.cc.i

src/data_frame.s: src/data_frame.cc.s
.PHONY : src/data_frame.s

# target to generate assembly for a file
src/data_frame.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sensor_compress.dir/build.make CMakeFiles/sensor_compress.dir/src/data_frame.cc.s
.PHONY : src/data_frame.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sensor_compress"
	@echo "... src/compress.o"
	@echo "... src/compress.i"
	@echo "... src/compress.s"
	@echo "... src/data_frame.o"
	@echo "... src/data_frame.i"
	@echo "... src/data_frame.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /Users/robk/src/tryhard/esp/lib/sensor_compress/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

