/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_SENSOR_COMPRESS_PROTO_INCLUDE_PROTO_SENSOR_PB_H_INCLUDED
#define PB_SENSOR_COMPRESS_PROTO_INCLUDE_PROTO_SENSOR_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _sensor_compress_proto_TestMessageWithOptions {
    char str[16];
} sensor_compress_proto_TestMessageWithOptions;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define sensor_compress_proto_TestMessageWithOptions_init_default {""}
#define sensor_compress_proto_TestMessageWithOptions_init_zero {""}

/* Field tags (for use in manual encoding/decoding) */
#define sensor_compress_proto_TestMessageWithOptions_str_tag 1

/* Struct field encoding specification for nanopb */
#define sensor_compress_proto_TestMessageWithOptions_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   str,               1)
#define sensor_compress_proto_TestMessageWithOptions_CALLBACK NULL
#define sensor_compress_proto_TestMessageWithOptions_DEFAULT NULL

extern const pb_msgdesc_t sensor_compress_proto_TestMessageWithOptions_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define sensor_compress_proto_TestMessageWithOptions_fields &sensor_compress_proto_TestMessageWithOptions_msg

/* Maximum encoded size of messages (where known) */
#define SENSOR_COMPRESS_PROTO_INCLUDE_PROTO_SENSOR_PB_H_MAX_SIZE sensor_compress_proto_TestMessageWithOptions_size
#define sensor_compress_proto_TestMessageWithOptions_size 17

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
